### ISSUE TITLE
Module roadmap V3.1

### ISSUE THREAD

**Issue by GuusLieben** [GuusLieben/DarwinServer#38]
**This is a raw list of modules to be converted and should not be used as reference material for open issues**
**Player modules**
- **PlayerData**
    - [ ] OldPlots
        - [ ] Database reading and model conversion
        - [ ] Teleportation actions
    - [ ] Locate (defaults to world name)
        - [ ] Plot flag (`--plot` `-p`)
- **Friends**
    - [ ] _Roadmap required_!
- **Move Actions**
    - [ ] Gamemode check on teleportation (no Spectator)
        - [ ] Whitelist/blacklist configuration for worlds where the check is disabled (e.g. Viggoman)
    - [ ] World (config) allowed check on move
        - [ ] Whitelist/blacklist configuration for allowed worlds
    - [ ] Plot world allowed check on move
        - [ ] Denied
        - [ ] Not owner
        - [ ] World format check

**Server modules**
- **Archival**
    - [ ] _Roadmap required_!
- **World unloader**
    - [ ] WorldUnloader command to add world to unload blacklist (`/wu add [world]`)
    - [ ] Unload worlds every 2 minutes, with a max of 10 worlds per run

**WorldEdit modules**
- **Schematic Brush**
    - [ ] _Roadmap required_! Waiting for WorldEdit API
- **Brush Tooltips**
    - [ ] _Roadmap required_! Waiting for WorldEdit API
- **PaletteSwap**
    - [ ] _Roadmap required_! Waiting for WorldEdit API
- **LayerSwap**
    - [ ] _Roadmap required_! Waiting for WorldEdit API
- **LayerHeight**
    - [ ] _Roadmap required_! Waiting for WorldEdit API

**Other modules**
- **Dave**
    - [ ] _Roadmap required_! Waiting for Discord API
- **Heads Evolved**
    - [ ] _Roadmap required_! Waiting for Chest UI API
- **Hotbar Share**
    - [ ] _Roadmap required_!
- **Modular Wiki**
    - [ ] _Roadmap required_!
- **Painting Submissions**
    - [ ] _Roadmap required_! Waiting for Discord API
- **Plot ID Bar**
    - [ ] _Roadmap required_! Waiting for Bossbar API
- **Plot Trust Limit** 
    - [ ] _Roadmap required_! Waiting for P2 API
- **Tickets**
    - [ ] _Roadmap required_! Waiting for P2 and Pagination API
